import { Link, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { ArrowRight, Bell, BookOpen, Building2, CalendarDays, CheckCircle2, ChevronDown, ClipboardCheck, Download, FileText, Filter, Globe2, GraduationCap, HelpCircle, Mail, MapPin, Menu, Newspaper, Phone, Search, ShoppingCart, Sparkles, Star, Trophy, Upload, User, Users, Wallet, X } from 'lucide-react'
import { useState, type ReactNode } from 'react'

type Exam = { slug: string; title: string; short: string; category: string; date: string; status: string; mode: string; color: string }
type Product = { slug: string; title: string; type: string; category: string; level: string; format: string; price: number; oldPrice?: number; badge: string; rating: number; sold: number; cover: string; desc: string }
type News = { slug: string; title: string; category: string; date: string; views: string }
type Partner = { slug: string; name: string; type: string; desc: string; year: string }

const exams: Exam[] = [
  { slug: 'iaio-2024', title: 'IAIO 2024 - Vòng quốc gia', short: 'Kỳ thi Trí tuệ nhân tạo Quốc tế dành cho học sinh lớp 8 - 12.', category: 'AI', date: '10/05/2024', status: 'Đang mở đăng ký', mode: 'Online', color: 'from-indigo-950 to-blue-700' },
  { slug: 'ico-2024', title: 'ICO 2024 - Vòng quốc gia', short: 'Kỳ thi Lập trình Quốc tế, đánh giá năng lực lập trình và tư duy thuật toán.', category: 'Lập trình', date: '08/06/2024', status: 'Đang mở đăng ký', mode: 'Online', color: 'from-sky-950 to-cyan-700' },
  { slug: 'robotics-stem-2024', title: 'Robotics & STEM Challenge', short: 'Sân chơi sáng tạo công nghệ, robot, kỹ thuật và giải quyết vấn đề.', category: 'Robotics', date: '05/07/2024', status: 'Đang mở đăng ký', mode: 'Trực tiếp', color: 'from-emerald-950 to-green-700' },
  { slug: 'math-olympiad', title: 'Kỳ thi Toán học Quốc tế', short: 'Rèn luyện tư duy logic, kỹ năng giải quyết vấn đề và năng lực toán học.', category: 'Toán học', date: '15/06/2024', status: 'Đang mở đăng ký', mode: 'Trực tiếp', color: 'from-slate-950 to-slate-700' },
  { slug: 'science-olympiad', title: 'Kỳ thi Khoa học Quốc tế', short: 'Đánh giá năng lực khoa học tự nhiên, phân tích và thực nghiệm.', category: 'Khoa học', date: '20/07/2024', status: 'Sắp mở đăng ký', mode: 'Online', color: 'from-cyan-950 to-blue-700' },
  { slug: 'stem-lab', title: 'STEM Innovation Lab', short: 'Dành cho học sinh yêu thích sáng tạo, mô hình hóa và thuyết trình dự án.', category: 'STEM', date: '10/07/2024', status: 'Sắp mở đăng ký', mode: 'Online', color: 'from-purple-950 to-indigo-700' },
]
const products: Product[] = [
  { slug: 'robotics-nang-cao', title: 'Sách luyện thi Robotics nâng cao 2024', type: 'Sách in + PDF', category: 'Robotics', level: 'Lớp 8-12', format: 'Sách/PDF', price: 249000, oldPrice: 320000, badge: 'Bán chạy', rating: 4.9, sold: 382, cover: '🤖', desc: 'Bộ chuyên đề Robotics nâng cao, có bài tập thực hành và hướng dẫn giải.' },
  { slug: 'iaio-de-thi-thu', title: 'Bộ đề thi thử IAIO 2024', type: 'Tài liệu số', category: 'AI', level: 'Lớp 8-12', format: 'PDF', price: 99000, oldPrice: 150000, badge: 'Mới', rating: 4.8, sold: 268, cover: '🧠', desc: 'Đề thi thử IAIO có đáp án, phân tích tư duy và gợi ý ôn tập.' },
  { slug: 'python-co-ban', title: 'Lập trình Python cơ bản cho học sinh', type: 'Sách điện tử', category: 'Lập trình', level: 'Lớp 6-9', format: 'PDF/DOCX', price: 129000, badge: 'Nên mua', rating: 4.7, sold: 514, cover: '💻', desc: 'Lộ trình Python nền tảng, phù hợp học sinh mới bắt đầu lập trình.' },
  { slug: 'cong-thuc-toan', title: 'Sổ tay công thức Toán 10 - 12', type: 'Tài liệu số', category: 'Toán học', level: 'THPT', format: 'PDF', price: 0, badge: 'Miễn phí', rating: 4.6, sold: 1205, cover: '📐', desc: 'Tổng hợp công thức quan trọng, trình bày ngắn gọn, dễ tra cứu.' },
  { slug: 'hoa-hoc-12', title: '3000 bài tập Hóa học 12 có đáp án', type: 'Bộ đề', category: 'Khoa học', level: 'Lớp 12', format: 'XLSX/PDF', price: 179000, oldPrice: 240000, badge: 'Ưu đãi', rating: 4.8, sold: 231, cover: '🧪', desc: 'Kho bài tập Hóa học 12, có đáp án và phân loại mức độ.' },
  { slug: 'stem-projects', title: 'STEM Project Ideas 2024', type: 'Ebook', category: 'STEM', level: 'Lớp 6-12', format: 'PDF', price: 89000, badge: 'Hot', rating: 4.7, sold: 174, cover: '🚀', desc: 'Ý tưởng dự án STEM để luyện tư duy sáng tạo và thuyết trình.' },
]
const news: News[] = [
  { slug: 'ket-qua-icao-2024', title: 'Kết quả vòng quốc gia ICAO 2024 - Thông báo chính thức', category: 'Kết quả', date: '10/05/2024', views: '2.4K' },
  { slug: 'lich-thi-ico-2024', title: 'Thông báo lịch thi ICO 2024 - Vòng quốc gia', category: 'Thông báo', date: '08/05/2024', views: '1.2K' },
  { slug: 'hoi-nghi-khao-thi-stem', title: 'FermatTech tổ chức Hội nghị Khảo thí STEM 2024', category: 'Sự kiện', date: '05/05/2024', views: '856' },
  { slug: 'bao-mat-tai-khoan', title: 'Hướng dẫn bảo mật tài khoản và thông tin cá nhân', category: 'Cẩm nang', date: '04/05/2024', views: '950' },
]
const partners: Partner[] = [
  { slug: 'google-for-education', name: 'Google for Education', type: 'Công nghệ', desc: 'Hỗ trợ công cụ và tài nguyên giúp nâng cao trải nghiệm học tập số.', year: '2022' },
  { slug: 'microsoft', name: 'Microsoft', type: 'Công nghệ', desc: 'Đồng hành thúc đẩy chuyển đổi số giáo dục và AI trong học tập.', year: '2023' },
  { slug: 'meta', name: 'Meta', type: 'Công nghệ', desc: 'Hợp tác trong các dự án giáo dục STEM, kỹ năng số và cộng đồng số.', year: '2024' },
  { slug: 'viettel', name: 'Viettel', type: 'Doanh nghiệp', desc: 'Kết nối hạ tầng nền tảng, thúc đẩy giáo dục số đến mọi miền.', year: '2023' },
  { slug: 'fpt', name: 'FPT Corporation', type: 'Công nghệ', desc: 'Đồng hành triển khai giải pháp công nghệ phục vụ giáo dục thông minh.', year: '2023' },
  { slug: 'bkacad', name: 'BKACAD', type: 'STEM', desc: 'Đào tạo và phát triển nguồn nhân lực kỹ thuật cao trong lĩnh vực công nghệ.', year: '2022' },
]
const faqs = ['Làm thế nào để đăng ký tham gia kỳ thi?', 'Khi nào có kết quả thi?', 'Lệ phí thi được thanh toán như thế nào?', 'Tôi quên số báo danh thì phải làm sao?', 'Kỳ thi được tổ chức online hay offline?', 'Thông tin cá nhân có được bảo mật không?']
const cn = (...c: Array<string | false | undefined>) => c.filter(Boolean).join(' ')
const money = (n: number) => n === 0 ? 'Miễn phí' : new Intl.NumberFormat('vi-VN').format(n) + 'đ'

function Button({ children, to, variant = 'primary', className = '', onClick }: { children: ReactNode; to?: string; variant?: 'primary' | 'secondary' | 'ghost'; className?: string; onClick?: () => void }) { const base = 'inline-flex items-center justify-center gap-2 rounded-2xl px-5 py-3 text-sm font-bold transition focus:outline-none focus:ring-4 focus:ring-blue-100'; const styles = { primary: 'bg-blue-600 text-white shadow-card hover:bg-blue-700', secondary: 'border border-blue-200 bg-white text-blue-700 hover:bg-blue-50', ghost: 'text-blue-700 hover:bg-blue-50' }; const cls = cn(base, styles[variant], className); return to ? <Link className={cls} to={to}>{children}</Link> : <button className={cls} onClick={onClick}>{children}</button> }
function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <div className={cn('rounded-3xl border border-slate-200 bg-white p-6 shadow-card', className)}>{children}</div> }
function Badge({ children, color = 'blue' }: { children: ReactNode; color?: 'blue' | 'green' | 'orange' | 'purple' | 'slate' }) { const colors = { blue: 'bg-blue-50 text-blue-700', green: 'bg-emerald-50 text-emerald-700', orange: 'bg-orange-50 text-orange-700', purple: 'bg-purple-50 text-purple-700', slate: 'bg-slate-100 text-slate-600' }; return <span className={cn('inline-flex rounded-full px-3 py-1 text-xs font-bold', colors[color])}>{children}</span> }
function Header() { const [open, setOpen] = useState(false); const nav = [['Trang chủ', '/'], ['Kỳ thi', '/ky-thi'], ['Tài liệu', '/tai-lieu'], ['Tra cứu điểm', '/tra-cuu-diem'], ['Tin tức', '/tin-tuc'], ['Liên hệ', '/lien-he'], ['Giới thiệu', '/gioi-thieu']]; return <header className="sticky top-0 z-50 border-b border-slate-200/70 bg-white/95 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 lg:px-8"><Link to="/" className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-600 text-white shadow-card"><Sparkles size={22} /></div><div><div className="text-xl font-extrabold text-slate-950">FermatTech</div><div className="text-xs font-bold text-blue-600">Khảo thí</div></div></Link><nav className="hidden items-center gap-2 lg:flex">{nav.map(([label, path]) => <NavLink key={path} to={path} className={({ isActive }) => cn('rounded-xl px-4 py-2 text-sm font-semibold transition', isActive ? 'bg-blue-50 text-blue-700' : 'text-slate-700 hover:bg-slate-50')}>{label}</NavLink>)}</nav><div className="flex items-center gap-2"><Button to="/dang-ky" className="hidden sm:inline-flex">Đăng ký ngay</Button><button onClick={() => setOpen(!open)} className="rounded-xl border border-slate-200 p-3 lg:hidden">{open ? <X size={20} /> : <Menu size={20} />}</button></div></div>{open && <div className="border-t border-slate-100 bg-white px-4 py-4 lg:hidden"><div className="grid gap-2">{nav.map(([label, path]) => <NavLink onClick={() => setOpen(false)} key={path} to={path} className={({ isActive }) => cn('rounded-xl px-4 py-3 text-sm font-bold', isActive ? 'bg-blue-50 text-blue-700' : 'text-slate-700')}>{label}</NavLink>)}</div></div>}</header> }
function Footer() { return <footer className="mt-16 bg-blue-700 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-12 md:grid-cols-4 lg:px-8"><div><div className="mb-3 text-2xl font-extrabold">FermatTech</div><p className="text-sm leading-6 text-blue-100">Nền tảng khảo thí và cuộc thi quốc tế uy tín hàng đầu dành cho học sinh Việt Nam.</p></div><div><h3 className="font-bold">Liên kết nhanh</h3><div className="mt-4 grid gap-2 text-sm text-blue-100"><Link to="/ky-thi">Kỳ thi</Link><Link to="/tai-lieu">Tài liệu</Link><Link to="/tra-cuu-diem">Tra cứu điểm</Link><Link to="/tin-tuc">Tin tức</Link></div></div><div><h3 className="font-bold">Về chúng tôi</h3><div className="mt-4 grid gap-2 text-sm text-blue-100"><Link to="/gioi-thieu">Giới thiệu</Link><Link to="/doi-tac">Đối tác</Link><Link to="/faq">FAQ</Link><Link to="/lien-he">Liên hệ</Link></div></div><div><h3 className="font-bold">Đăng ký nhận tin</h3><p className="mt-4 text-sm text-blue-100">Nhận thông tin mới nhất về kỳ thi, sự kiện và tài liệu.</p><div className="mt-5 flex rounded-2xl bg-blue-800 p-2"><input className="min-w-0 flex-1 bg-transparent px-3 text-sm outline-none placeholder:text-blue-200" placeholder="Nhập email của bạn" /><button className="rounded-xl bg-blue-500 p-3"><ArrowRight size={18} /></button></div></div></div><div className="border-t border-blue-500/40 py-5 text-center text-xs text-blue-100">© 2024 FermatTech Khảo thí.</div></footer> }
function Layout({ children }: { children: ReactNode }) { return <div className="min-h-screen bg-slate-50"><Header /><main>{children}</main><Footer /></div> }
function PageHero({ title, desc, icon }: { title: string; desc: string; icon?: ReactNode }) { return <section className="relative overflow-hidden bg-gradient-to-br from-white to-blue-50"><div className="absolute right-0 top-0 h-full w-1/2 bg-grid opacity-50" /><div className="relative mx-auto flex max-w-7xl items-center justify-between gap-10 px-4 py-16 lg:px-8"><div className="max-w-3xl"><div className="mb-4 text-sm font-bold text-blue-600">Trang chủ / {title}</div><h1 className="text-4xl font-extrabold tracking-tight text-slate-950 md:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">{desc}</p></div><div className="hidden h-56 w-80 items-center justify-center rounded-[2rem] bg-white shadow-soft lg:flex"><div className="text-blue-600">{icon ?? <Sparkles size={90} />}</div></div></div></section> }
function SectionTitle({ title, to }: { title: string; to?: string }) { return <div className="mb-6 mt-12 flex items-center justify-between"><h2 className="text-2xl font-extrabold text-slate-950 md:text-3xl">{title}</h2>{to && <Link to={to} className="text-sm font-bold text-blue-600">Xem tất cả →</Link>}</div> }
function StatCard({ icon, value, label, color = 'text-blue-600' }: { icon: ReactNode; value: string; label: string; color?: string }) { return <Card className="flex items-center gap-4 p-5"><div className="rounded-2xl bg-blue-50 p-4 text-blue-600">{icon}</div><div><div className={cn('text-2xl font-extrabold', color)}>{value}</div><div className="text-sm font-medium text-slate-500">{label}</div></div></Card> }
function ExamCard({ exam }: { exam: Exam }) { return <Card className="card-hover overflow-hidden p-0"><div className={cn('h-36 bg-gradient-to-br p-6 text-white', exam.color)}><Badge color="slate">{exam.category}</Badge><h3 className="mt-5 text-2xl font-extrabold">{exam.title.split('-')[0]}</h3></div><div className="p-6"><h3 className="text-lg font-bold text-slate-950">{exam.title}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-slate-600">{exam.short}</p><div className="mt-5 grid grid-cols-2 gap-3 text-sm text-slate-600"><span className="flex items-center gap-2"><CalendarDays size={16} />{exam.date}</span><span className="flex items-center gap-2"><Globe2 size={16} />{exam.mode}</span></div><div className="mt-5 flex items-center justify-between"><Badge color={exam.status.includes('Đang') ? 'green' : 'orange'}>{exam.status}</Badge><Button to={`/ky-thi/${exam.slug}`} variant="secondary" className="px-4 py-2">Xem chi tiết</Button></div></div></Card> }
function ProductCard({ item }: { item: Product }) { return <Card className="card-hover group overflow-hidden p-0"><Link to={`/tai-lieu/${item.slug}`} className="block"><div className="relative flex h-56 items-center justify-center bg-gradient-to-br from-blue-50 to-slate-100"><div className="absolute left-4 top-4 z-10"><Badge color={item.price === 0 ? 'green' : item.badge === 'Ưu đãi' ? 'orange' : 'blue'}>{item.badge}</Badge></div><div className="absolute right-4 top-4 rounded-full bg-white/90 px-3 py-1 text-xs font-bold text-slate-600 shadow-card">{item.format}</div><div className="text-7xl transition group-hover:scale-110">{item.cover}</div></div></Link><div className="p-5"><div className="flex flex-wrap gap-2"><Badge color="slate">{item.category}</Badge><Badge color="purple">{item.level}</Badge></div><Link to={`/tai-lieu/${item.slug}`} className="mt-4 block min-h-14 text-lg font-extrabold leading-7 text-slate-950 hover:text-blue-600">{item.title}</Link><p className="mt-2 line-clamp-2 min-h-12 text-sm leading-6 text-slate-500">{item.desc}</p><div className="mt-4 flex items-center justify-between text-sm"><span className="font-bold text-amber-500">★ {item.rating}</span><span className="text-slate-400">Đã bán {item.sold}</span></div><div className="mt-4 flex items-end justify-between gap-3"><div><div className={cn('text-2xl font-extrabold', item.price === 0 ? 'text-emerald-600' : 'text-blue-600')}>{money(item.price)}</div>{item.oldPrice && <div className="text-sm text-slate-400 line-through">{money(item.oldPrice)}</div>}</div><Button to={`/tai-lieu/${item.slug}`} className="px-4 py-2"><ShoppingCart size={16} />{item.price === 0 ? 'Tải' : 'Mua'}</Button></div></div></Card> }
function NewsCard({ item }: { item: News }) { return <Card className="card-hover overflow-hidden p-0"><div className="h-40 bg-gradient-to-br from-slate-900 to-blue-700" /><div className="p-5"><Badge>{item.category}</Badge><Link to={`/tin-tuc/${item.slug}`} className="mt-4 block text-lg font-bold leading-7 text-slate-950 hover:text-blue-600">{item.title}</Link><div className="mt-4 flex items-center gap-4 text-xs text-slate-500"><span>{item.date}</span><span>👁 {item.views}</span></div></div></Card> }
function PartnerCard({ partner }: { partner: Partner }) { return <Card className="card-hover"><div className="flex items-start justify-between"><div className="text-2xl font-extrabold text-slate-950">{partner.name}</div><Badge>{partner.type}</Badge></div><p className="mt-4 min-h-16 text-sm leading-6 text-slate-600">{partner.desc}</p><Button to={`/doi-tac/${partner.slug}`} variant="secondary" className="mt-6 w-full">Xem chi tiết</Button></Card> }
function SearchFilter({ placeholder = 'Tìm kiếm...' }: { placeholder?: string }) { return <Card className="flex flex-col gap-4 md:flex-row md:items-center"><div className="flex flex-1 items-center gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3"><Search size={20} className="text-slate-400" /><input placeholder={placeholder} className="w-full bg-transparent text-sm outline-none" /></div><div className="grid grid-cols-2 gap-3 md:flex"><Button variant="secondary"><Filter size={16} />Bộ lọc</Button><Button variant="secondary">Cấp học</Button><Button variant="secondary">Lĩnh vực</Button><Button variant="secondary">Giá</Button></div></Card> }
function Input({ label, placeholder, textarea }: { label: string; placeholder: string; textarea?: boolean }) { return <label className="block"><span className="text-sm font-bold text-slate-700">{label}</span>{textarea ? <textarea className="mt-2 min-h-32 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-blue-400" placeholder={placeholder} /> : <input className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-blue-400" placeholder={placeholder} />}</label> }
function PartnersStrip() { return <div className="mt-14"><h2 className="mb-5 text-center text-xl font-extrabold">Đối tác / Đơn vị đồng hành</h2><Card className="grid grid-cols-2 gap-4 text-center text-xl font-extrabold text-slate-400 md:grid-cols-4 lg:grid-cols-8">{['Google', 'Microsoft', 'AWS', 'Meta', 'Viettel', 'FPT', 'Vingroup', 'BKACAD'].map(x => <div key={x}>{x}</div>)}</Card></div> }
function FAQSmall() { return <div className="mt-12"><h2 className="mb-5 text-2xl font-extrabold">Câu hỏi thường gặp</h2><div className="grid gap-4 md:grid-cols-2">{faqs.slice(0, 6).map(q => <Card key={q} className="flex items-center justify-between p-4"><span className="font-semibold text-slate-700">{q}</span><ChevronDown className="text-slate-400" size={18} /></Card>)}</div></div> }
function Info({ label, value, green }: { label: string; value: string; green?: boolean }) { return <div><p className="text-sm text-slate-500">{label}</p><p className={cn('mt-1 text-lg font-extrabold', green ? 'text-emerald-600' : 'text-slate-950')}>{value}</p></div> }
function ContactItem({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div className="mt-6 flex gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-blue-600">{icon}</div><div><b>{title}</b><p className="mt-1 text-sm text-slate-600">{text}</p></div></div> }

function HomePage() { return <Layout><section className="relative overflow-hidden bg-gradient-to-br from-white via-blue-50 to-white"><div className="absolute right-0 top-20 h-96 w-1/2 rounded-l-[5rem] bg-blue-100/60" /><div className="relative mx-auto grid max-w-7xl items-center gap-12 px-4 py-20 lg:grid-cols-2 lg:px-8"><div><h1 className="text-4xl font-extrabold leading-tight tracking-tight text-slate-950 md:text-6xl">Nền tảng <span className="text-gradient">khảo thí</span> và cuộc thi quốc tế dành cho học sinh</h1><p className="mt-6 text-lg leading-8 text-slate-600">FermatTech Khảo thí mang đến các kỳ thi học thuật và STEM chuẩn quốc tế, giúp học sinh Việt Nam chinh phục tri thức.</p><div className="mt-8 flex flex-wrap gap-4"><Button to="/ky-thi">Khám phá kỳ thi <ArrowRight size={18} /></Button><Button to="/tra-cuu-diem" variant="secondary">Tra cứu điểm <Search size={18} /></Button></div></div><Card className="p-7"><h3 className="text-2xl font-bold">Bảng điều khiển học sinh</h3><div className="mt-5 grid gap-4 md:grid-cols-2"><Card className="p-4"><b>Kỳ thi sắp tới</b><p className="mt-2 text-sm text-slate-500">ICO 2024 - Vòng quốc gia</p></Card><Card className="p-4"><b>Kết quả gần nhất</b><div className="mt-3 text-3xl font-extrabold text-blue-600">85/100</div></Card></div></Card></div></section><section className="mx-auto max-w-7xl px-4 py-12 lg:px-8"><div className="grid gap-5 md:grid-cols-4"><StatCard icon={<Trophy />} value="28+" label="Kỳ thi quốc tế" /><StatCard icon={<Users />} value="125.000+" label="Thí sinh tham gia" color="text-emerald-600" /><StatCard icon={<Building2 />} value="1.250+" label="Trường tham gia" color="text-orange-600" /><StatCard icon={<FileText />} value="3.600+" label="Tài liệu học thuật" color="text-purple-600" /></div><SectionTitle title="Kỳ thi nổi bật" to="/ky-thi" /><div className="grid gap-6 lg:grid-cols-3">{exams.slice(0, 3).map(e => <ExamCard key={e.slug} exam={e} />)}</div><SectionTitle title="Gian hàng tài liệu nổi bật" to="/tai-lieu" /><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{products.slice(0, 4).map(p => <ProductCard key={p.slug} item={p} />)}</div><PartnersStrip /><FAQSmall /></section></Layout> }
function ExamsPage() { return <Layout><PageHero title="Khám phá các kỳ thi" desc="Tìm kiếm và đăng ký các kỳ thi phù hợp với năng lực và định hướng của bạn." icon={<ClipboardCheck size={96} />} /><section className="mx-auto max-w-7xl px-4 py-10 lg:px-8"><SearchFilter placeholder="Tìm kiếm kỳ thi, lĩnh vực, cấp học..." /><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_320px]"><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{exams.map(e => <ExamCard key={e.slug} exam={e} />)}</div><Card className="h-fit"><h3 className="text-xl font-extrabold">Lịch thi sắp tới</h3>{exams.slice(0, 5).map(e => <div key={e.slug} className="mt-5 border-b border-slate-100 pb-4 last:border-0"><Badge>{e.category}</Badge><div className="mt-2 font-bold">{e.title}</div><div className="mt-1 text-sm text-slate-500">{e.date}</div></div>)}</Card></div></section></Layout> }
function DocumentsPage() { const categories = ['Tất cả', 'Sách ôn thi', 'Tài liệu số', 'Combo', 'Miễn phí', 'Bán chạy']; return <Layout><section className="bg-gradient-to-br from-blue-700 via-blue-600 to-indigo-700 text-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-14 lg:grid-cols-[1fr_360px] lg:px-8"><div><Badge color="slate">GIAN HÀNG HỌC THUẬT</Badge><h1 className="mt-5 text-4xl font-extrabold leading-tight md:text-6xl">Sách, bộ đề và tài liệu ôn luyện</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-blue-100">Trang tài liệu được thiết kế theo mô hình gian hàng: có sách miễn phí, tài liệu trả phí, combo ôn thi và sản phẩm bán chạy.</p><div className="mt-8 flex flex-wrap gap-4"><Button variant="secondary"><ShoppingCart size={18} />Xem sản phẩm</Button><Button variant="ghost" className="bg-white/10 text-white hover:bg-white/20">Chính sách mua tài liệu</Button></div></div><Card className="bg-white/95 text-slate-950"><h3 className="text-xl font-extrabold">Ưu đãi hôm nay</h3><p className="mt-3 text-sm text-slate-600">Giảm tới 30% cho các bộ đề IAIO, ICO, Robotics khi mua theo combo.</p><div className="mt-5 rounded-2xl bg-orange-50 p-4 text-orange-700"><b>Flash sale</b><p className="text-sm">Còn 08:32:41</p></div></Card></div></section><section className="mx-auto max-w-7xl px-4 py-10 lg:px-8"><SearchFilter placeholder="Tìm sách, bộ đề, ebook, tài liệu ôn luyện..." /><div className="mt-6 flex flex-wrap gap-3">{categories.map((c, i) => <Badge key={c} color={i === 0 ? 'blue' : c === 'Miễn phí' ? 'green' : 'slate'}>{c}</Badge>)}</div><div className="mt-8 grid gap-8 lg:grid-cols-[260px_1fr]"><aside className="space-y-6"><Card><h3 className="text-xl font-extrabold">Bộ lọc gian hàng</h3><div className="mt-5 space-y-4 text-sm text-slate-600"><p><b>Khoảng giá</b></p><p>□ Miễn phí</p><p>□ Dưới 100.000đ</p><p>□ 100.000đ - 200.000đ</p><p>□ Trên 200.000đ</p><p className="pt-3"><b>Định dạng</b></p><p>□ Sách in</p><p>□ PDF/Ebook</p><p>□ Combo</p></div></Card><Card className="bg-blue-50"><h3 className="text-lg font-extrabold">Cam kết</h3><p className="mt-3 text-sm leading-6 text-slate-600">Tài liệu được biên soạn bởi đội ngũ FermatTech, có thể mở rộng thanh toán và cấp quyền tải sau này.</p></Card></aside><main><div className="mb-5 flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><h2 className="text-2xl font-extrabold">Sản phẩm nổi bật</h2><p className="mt-1 text-sm text-slate-500">Hiển thị theo dạng gian hàng, sẵn sàng mở rộng bán sách/tài liệu trả phí.</p></div><Button variant="secondary">Sắp xếp: Bán chạy</Button></div><div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-3">{products.map(p => <ProductCard key={p.slug} item={p} />)}</div></main></div></section></Layout> }
function LookupPage() { const navigate = useNavigate(); return <Layout><PageHero title="Tra cứu kết quả kỳ thi" desc="Nhập thông tin của bạn để xem kết quả kỳ thi." icon={<Search size={96} />} /><section className="mx-auto grid max-w-7xl gap-8 px-4 py-10 lg:grid-cols-[1fr_420px] lg:px-8"><Card><h2 className="text-2xl font-extrabold">Nhập thông tin tra cứu</h2><div className="mt-8 grid gap-5 md:grid-cols-2"><Input label="Số báo danh" placeholder="Nhập số báo danh" /><Input label="Họ và tên" placeholder="Nhập họ và tên" /><Input label="Kỳ thi" placeholder="Chọn kỳ thi" /><Input label="Năm dự thi" placeholder="Chọn năm" /></div><Button className="mt-8 w-full" onClick={() => navigate('/tra-cuu-diem/ket-qua')}>Tra cứu</Button></Card><Card><h3 className="text-xl font-extrabold">Kết quả mẫu</h3><div className="mt-4 text-4xl font-extrabold text-blue-600">35.50</div></Card></section></Layout> }
function NewsPage() { return <Layout><PageHero title="Tin tức & thông báo" desc="Cập nhật những thông tin mới nhất từ FermatTech Khảo thí." icon={<Newspaper size={96} />} /><section className="mx-auto max-w-7xl px-4 py-10 lg:px-8"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{news.map(n => <NewsCard key={n.slug} item={n} />)}</div></section></Layout> }
function ContactPage() { return <Layout><PageHero title="Liên hệ với chúng tôi" desc="FermatTech Khảo thí luôn sẵn sàng hỗ trợ." icon={<Mail size={96} />} /><section className="mx-auto grid max-w-7xl gap-8 px-4 py-10 lg:grid-cols-[420px_1fr] lg:px-8"><Card><h2 className="text-2xl font-extrabold">Thông tin liên hệ</h2><ContactItem icon={<Phone />} title="Hotline" text="1900 433 330" /><ContactItem icon={<Mail />} title="Email" text="support@fermattech.edu.vn" /><ContactItem icon={<MapPin />} title="Địa chỉ" text="TP. Hồ Chí Minh" /></Card><Card><h2 className="text-2xl font-extrabold">Gửi yêu cầu liên hệ</h2><div className="mt-8 grid gap-5 md:grid-cols-2"><Input label="Họ và tên" placeholder="Nhập họ và tên" /><Input label="Email" placeholder="Nhập email" /><Input label="Số điện thoại" placeholder="Nhập số điện thoại" /><Input label="Chủ đề" placeholder="Chọn chủ đề" /><div className="md:col-span-2"><Input label="Nội dung" placeholder="Nhập nội dung" textarea /></div></div><Button className="mt-6">Gửi liên hệ</Button></Card></section></Layout> }
function ExamDetailPage() { const { slug } = useParams(); const exam = exams.find(e => e.slug === slug) ?? exams[0]; return <Layout><section className="mx-auto grid max-w-7xl gap-8 px-4 py-10 lg:grid-cols-[1fr_340px] lg:px-8"><main><div className={cn('rounded-[2rem] bg-gradient-to-br p-10 text-white', exam.color)}><Badge color="slate">{exam.category}</Badge><h1 className="mt-6 text-4xl font-extrabold">{exam.title}</h1><p className="mt-4 max-w-2xl text-blue-50">{exam.short}</p></div><div className="mt-8 grid gap-4 md:grid-cols-4"><StatCard icon={<Users />} value="Lớp 8-12" label="Đối tượng" /><StatCard icon={<Globe2 />} value={exam.mode} label="Hình thức" /><StatCard icon={<CalendarDays />} value="90 phút" label="Thời gian" /><StatCard icon={<Wallet />} value="240.000đ" label="Lệ phí" /></div></main><aside><Card><h3 className="text-xl font-extrabold">Đăng ký</h3><Button to="/dang-ky" className="mt-5 w-full">Đăng ký ngay</Button></Card></aside></section></Layout> }
function DocumentDetailPage() { const { slug } = useParams(); const item = products.find(d => d.slug === slug) ?? products[0]; return <Layout><section className="mx-auto grid max-w-7xl gap-8 px-4 py-10 lg:grid-cols-[1fr_380px] lg:px-8"><main><Card className="overflow-hidden p-0"><div className="flex min-h-[420px] items-center justify-center bg-gradient-to-br from-blue-50 to-slate-100 text-9xl">{item.cover}</div></Card><Card className="mt-8"><h1 className="text-4xl font-extrabold">{item.title}</h1><p className="mt-4 leading-8 text-slate-600">{item.desc}</p><div className="mt-6 flex flex-wrap gap-2"><Badge>{item.category}</Badge><Badge color="purple">{item.level}</Badge><Badge color="slate">{item.type}</Badge></div></Card></main><aside className="space-y-6"><Card><Badge color={item.price === 0 ? 'green' : 'orange'}>{item.badge}</Badge><div className={cn('mt-5 text-4xl font-extrabold', item.price === 0 ? 'text-emerald-600' : 'text-blue-600')}>{money(item.price)}</div>{item.oldPrice && <div className="mt-2 text-slate-400 line-through">{money(item.oldPrice)}</div>}<div className="mt-5 flex items-center justify-between text-sm text-slate-500"><span>★ {item.rating}</span><span>Đã bán {item.sold}</span></div><Button className="mt-6 w-full"><ShoppingCart size={18} />{item.price === 0 ? 'Tải miễn phí' : 'Thêm vào giỏ hàng'}</Button><Button variant="secondary" className="mt-3 w-full">Mua ngay</Button></Card><Card><h3 className="text-xl font-extrabold">Thông tin sản phẩm</h3><div className="mt-4 space-y-2 text-sm text-slate-600"><p>Định dạng: {item.format}</p><p>Cấp học: {item.level}</p><p>Danh mục: {item.category}</p></div></Card></aside></section></Layout> }
function ResultSuccessPage() { return <Layout><PageHero title="Kết quả kỳ thi của bạn" desc="Chúc mừng bạn! Dưới đây là kết quả kỳ thi vừa tra cứu." icon={<Trophy size={96} />} /><section className="mx-auto max-w-7xl px-4 py-10 lg:px-8"><Card><div className="grid gap-8 lg:grid-cols-[1fr_280px]"><div className="grid gap-5 md:grid-cols-3"><Info label="Họ và tên" value="Nguyễn Minh Anh" /><Info label="Số báo danh" value="FT24051234" /><Info label="Kỳ thi" value="FermatTech Robotics" /><Info label="Trạng thái" value="Đạt" green /></div><div className="rounded-3xl border border-blue-100 bg-blue-50 p-6 text-center"><p className="font-bold text-slate-600">Tổng điểm</p><div className="mt-2 text-5xl font-extrabold text-blue-600">86.75</div></div></div></Card></section></Layout> }
function ArticleDetailPage() { const { slug } = useParams(); const item = news.find(n => n.slug === slug) ?? news[0]; return <Layout><section className="mx-auto max-w-4xl px-4 py-10 lg:px-8"><Badge>{item.category}</Badge><h1 className="mt-4 text-4xl font-extrabold leading-tight">{item.title}</h1><p className="mt-4 text-sm text-slate-500">{item.date} · {item.views} lượt xem</p><Card className="mt-8"><p className="leading-8 text-slate-600">FermatTech chính thức cập nhật thông tin mới nhất tới học sinh, phụ huynh và nhà trường.</p></Card></section></Layout> }
function AboutPage() { return <Layout><PageHero title="Giới thiệu FermatTech Khảo thí" desc="Nền tảng khảo thí và các cuộc thi quốc tế chuẩn quốc tế." icon={<GraduationCap size={96} />} /><section className="mx-auto max-w-7xl px-4 py-10 lg:px-8"><div className="grid gap-6 md:grid-cols-3"><Card><h3 className="text-xl font-extrabold">Sứ mệnh</h3><p className="mt-4 text-slate-600">Mang đến môi trường học thuật công bằng.</p></Card><Card><h3 className="text-xl font-extrabold">Tầm nhìn</h3><p className="mt-4 text-slate-600">Trở thành nền tảng khảo thí hàng đầu.</p></Card><Card><h3 className="text-xl font-extrabold">Giá trị cốt lõi</h3><p className="mt-4 text-slate-600">Uy tín, minh bạch, bảo mật.</p></Card></div><PartnersStrip /></section></Layout> }
function PartnersPage() { return <Layout><PageHero title="Đối tác & đơn vị đồng hành" desc="FermatTech hợp tác cùng các tổ chức giáo dục, công nghệ và doanh nghiệp uy tín." icon={<Users size={96} />} /><section className="mx-auto max-w-7xl px-4 py-10 lg:px-8"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{partners.map(p => <PartnerCard key={p.slug} partner={p} />)}</div></section></Layout> }
function PartnerDetailPage() { const { slug } = useParams(); const partner = partners.find(p => p.slug === slug) ?? partners[0]; return <Layout><section className="mx-auto max-w-7xl px-4 py-10 lg:px-8"><Card><Badge>Đối tác chiến lược</Badge><h1 className="mt-4 text-5xl font-extrabold">{partner.name}</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-600">{partner.desc}</p></Card></section></Layout> }
function RegisterPage() { const navigate = useNavigate(); return <Layout><PageHero title="Đăng ký tham gia kỳ thi" desc="Hoàn tất thông tin đăng ký theo từng bước." icon={<ClipboardCheck size={96} />} /><section className="mx-auto max-w-7xl px-4 py-10 lg:px-8"><Card><h2 className="text-2xl font-extrabold">Thông tin người đăng ký</h2><div className="mt-6 grid gap-5 md:grid-cols-3"><Input label="Họ và tên" placeholder="Nhập họ và tên" /><Input label="Ngày sinh" placeholder="DD/MM/YYYY" /><Input label="Email" placeholder="Nhập email" /></div><Button className="mt-8" onClick={() => navigate('/thanh-toan')}>Tiếp tục</Button></Card></section></Layout> }
function PaymentPage() { const navigate = useNavigate(); return <Layout><PageHero title="Thanh toán lệ phí" desc="Kiểm tra thông tin đơn đăng ký và lựa chọn phương thức thanh toán." icon={<Wallet size={96} />} /><section className="mx-auto max-w-7xl px-4 py-10 lg:px-8"><Card><h2 className="text-2xl font-extrabold">Phương thức thanh toán</h2><Button className="mt-6" onClick={() => navigate('/dang-ky-hoan-thanh')}>Xác nhận thanh toán</Button></Card></section></Layout> }
function RegisterSuccessPage() { return <Layout><PageHero title="Đăng ký thành công!" desc="Thông tin đăng ký của bạn đã được hệ thống ghi nhận." icon={<CheckCircle2 size={96} />} /></Layout> }
function FAQPage() { return <Layout><PageHero title="Câu hỏi thường gặp" desc="Tổng hợp các câu hỏi phổ biến." icon={<HelpCircle size={96} />} /><section className="mx-auto max-w-5xl px-4 py-10 lg:px-8">{faqs.concat(faqs).map((q, i) => <Card key={`${q}-${i}`} className="mb-4 flex items-center justify-between"><b>{q}</b><ChevronDown /></Card>)}</section></Layout> }
function AccountPage() { return <Layout><PageHero title="Tài khoản của tôi" desc="Theo dõi kỳ thi, kết quả và thông báo cá nhân." icon={<User size={96} />} /></Layout> }
function NotificationsPage() { return <Layout><PageHero title="Thông báo" desc="Theo dõi thông báo hệ thống, lịch thi, kết quả và tài liệu mới." icon={<Bell size={96} />} /></Layout> }
function NotFoundPage() { return <Layout><section className="mx-auto max-w-3xl px-4 py-24 text-center"><div className="text-8xl font-extrabold text-blue-600">404</div><h1 className="mt-6 text-4xl font-extrabold">Không tìm thấy trang</h1><div className="mt-8"><Button to="/">Về trang chủ</Button></div></section></Layout> }

export default function App() { return <Routes><Route path="/" element={<HomePage />} /><Route path="/ky-thi" element={<ExamsPage />} /><Route path="/ky-thi/:slug" element={<ExamDetailPage />} /><Route path="/tai-lieu" element={<DocumentsPage />} /><Route path="/tai-lieu/:slug" element={<DocumentDetailPage />} /><Route path="/tra-cuu-diem" element={<LookupPage />} /><Route path="/tra-cuu-diem/ket-qua" element={<ResultSuccessPage />} /><Route path="/tin-tuc" element={<NewsPage />} /><Route path="/tin-tuc/:slug" element={<ArticleDetailPage />} /><Route path="/lien-he" element={<ContactPage />} /><Route path="/gioi-thieu" element={<AboutPage />} /><Route path="/doi-tac" element={<PartnersPage />} /><Route path="/doi-tac/:slug" element={<PartnerDetailPage />} /><Route path="/dang-ky" element={<RegisterPage />} /><Route path="/thanh-toan" element={<PaymentPage />} /><Route path="/dang-ky-hoan-thanh" element={<RegisterSuccessPage />} /><Route path="/faq" element={<FAQPage />} /><Route path="/tai-khoan" element={<AccountPage />} /><Route path="/thong-bao" element={<NotificationsPage />} /><Route path="*" element={<NotFoundPage />} /></Routes> }
